# Generated by Django 4.2.3 on 2023-07-26 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice_app', '0003_basket_sum_price_service_in_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='sum_price',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='username',
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BasketService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice_app.basket')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice_app.service')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='services',
            field=models.ManyToManyField(through='autoservice_app.BasketService', to='autoservice_app.service'),
        ),
    ]
