# Generated by Django 4.2.3 on 2023-07-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice_app', '0004_remove_basket_sum_price_remove_basket_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketservice',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
