# Generated by Django 4.1.10 on 2023-08-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice_app', '0005_alter_basketservice_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='detail_name',
            new_name='service_name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='in_basket',
        ),
    ]
