# Generated by Django 4.1.10 on 2023-08-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice_app', '0006_rename_detail_name_order_service_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_name',
        ),
    ]
